version: '3'

services:
  python-map:
    build: .
    ports:
      - "8050:8050"
    depends_on:
      - postgis
    
  postgis: #default username should be postgres not rescue
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: rescuemate 
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: rescue@mate.com
      PGADMIN_DEFAULT_PASSWORD: rescuemate
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgis_data:
  pgadmin_data:
