version: '3'

services:
  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: rescuemate
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data: