version: '3'

services:
  python-map:
    build: 
      context: .
      dockerfile: docker/Dockerfile_map
    ports:
      - "8050:8050"
    depends_on:
      - postgis
    
  python-server-events:
    build: 
      context: .
      dockerfile: docker/Dockerfile_server_events
    ports:
      - "8051:8051"
    depends_on:
      - postgis
  
  python-server-nina:
    build: 
      context: .
      dockerfile: docker/Dockerfile_server_nina
    depends_on:
      - postgis
    
  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgis_data:
  pgadmin_data:
