version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8052:8052"
    depends_on:
      - postgis
    networks:
      - sems_network
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8050:80"
    depends_on:
      - backend
    networks:
      - sems_network
    restart: always

  server_reports:
    build:
      context: .
      dockerfile: docker/Dockerfile_server_reports
    depends_on:
      - postgis
    networks:
      - sems_network
    env_file:
      - .env
    restart: always

  postgis:
    image: postgis/postgis
    platform: linux/amd64
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      - sems_network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    platform: linux/amd64
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - sems_network
    restart: always

volumes:
  postgis_data:
  pgadmin_data:

networks:
  sems_network:
