/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials, open a session, set the httpOnly cookie. Returns 401 on
         *     bad username OR password (same message either way, so it can't be used to probe
         *     which usernames exist).
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who am I — used by the frontend on load to decide login-page vs app. 401
         *     (via the dependency) when there's no valid session.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reports Endpoint */
        get: operations["get_reports_endpoint_api_v1_reports__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/new-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** New Count Endpoint */
        get: operations["new_count_endpoint_api_v1_reports_new_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version Endpoint
         * @description Poll target: the frontend refetches the full bundle only when this
         *     token changes — see report_service.get_change_token.
         */
        get: operations["version_endpoint_api_v1_reports_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/dots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dots Endpoint */
        get: operations["dots_endpoint_api_v1_reports_dots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bundle Endpoint */
        get: operations["bundle_endpoint_api_v1_reports_bundle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/admit-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admit All Endpoint
         * @description Admission is a per-user watermark over ingestion order (see UserAdmission):
         *     admit-all simply advances it to the current max report id. Filters control
         *     what the user SEES; the watermark controls the "nothing appears without an
         *     explicit admit" property.
         */
        post: operations["admit_all_endpoint_api_v1_reports_admit_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/tour-example": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tour Example Endpoint */
        get: operations["tour_example_endpoint_api_v1_reports_tour_example_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report Endpoint */
        get: operations["get_report_endpoint_api_v1_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Hide Endpoint */
        patch: operations["hide_endpoint_api_v1_reports__report_id__hide_patch"];
        trace?: never;
    };
    "/api/v1/reports/{report_id}/flag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Flag Endpoint */
        patch: operations["flag_endpoint_api_v1_reports__report_id__flag_patch"];
        trace?: never;
    };
    "/api/v1/reports/{report_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Acknowledge Endpoint */
        patch: operations["acknowledge_endpoint_api_v1_reports__report_id__acknowledge_patch"];
        trace?: never;
    };
    "/api/v1/reports/{report_id}/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Restore Locations Endpoint */
        delete: operations["restore_locations_endpoint_api_v1_reports__report_id__locations_delete"];
        options?: never;
        head?: never;
        /** Update Locations Endpoint */
        patch: operations["update_locations_endpoint_api_v1_reports__report_id__locations_patch"];
        trace?: never;
    };
    "/api/v1/layers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Layers */
        get: operations["list_layers_api_v1_layers__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/layers/{layer_id}/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Layer Geojson */
        get: operations["layer_geojson_api_v1_layers__layer_id__geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_v1_scenarios__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenario Geojson */
        get: operations["scenario_geojson_api_v1_scenarios__scenario_id__geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * User State
         * @description Return the full aggregated state for the CURRENT user (derived from the
         *     session — a user can only read their own state):
         *       - admitted_up_to_id: int    — admission watermark; report ids <= this are
         *                                     admitted to the sidebar (see UserAdmission)
         *       - flagged_authors: list[str]
         *       - hide_ids: list[int]       — reports marked as seen/hidden
         *       - acknowledged_ids: list[int] — reports the user has explicitly opened
         *       - location_overrides: dict  — {str(report_id): list[LocationEntry]}
         */
        get: operations["user_state_api_v1_user_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geo/nominatim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nominatim Search
         * @description Proxy to Nominatim /search.
         *     Requests polygon_geojson=1 and returns a cleaned list of results.
         *     Returns [] on any error so the frontend can degrade gracefully.
         */
        get: operations["nominatim_search_api_v1_geo_nominatim_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Demo Status
         * @description Returns demo mode flag and current trickle progress.
         */
        get: operations["demo_status_api_v1_demo_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demo Reset
         * @description Clears all reports and user state, then trickles demo reports in one-by-one
         *     at the polling interval (10 s each).  Only available when DEMO_MODE=True.
         */
        post: operations["demo_reset_api_v1_demo_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DotDTO
         * @description A single map-dot, one per geocoded location (not one per report — a
         *     report with 3 locations yields 3 of these pre-clustering). Matches the dict
         *     build_dots() constructs; giving it a real schema (rather than list[dict])
         *     is what lets the frontend's DotDTO type be generated from this schema
         *     instead of hand-maintained in parallel.
         */
        DotDTO: {
            /** Report Id */
            report_id: number;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Seen */
            seen: boolean;
            /** Hide */
            hide: boolean;
            /** Flag */
            flag: boolean;
            /** New */
            new: boolean;
            /** Location Name */
            location_name: string;
            /** Location Display */
            location_display: string;
            /** Text */
            text: string;
            /** Author */
            author: string;
            /** Platform */
            platform: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Event Types
             * @default []
             */
            event_types: string[];
            /** Relevance */
            relevance: string;
            /** Url */
            url: string;
            /** Location Bbox Area */
            location_bbox_area?: number | null;
            /** Location Bbox */
            location_bbox?: number[] | null;
        };
        /** DotsResponse */
        DotsResponse: {
            /**
             * Dots
             * @default []
             */
            dots: components["schemas"]["DotDTO"][];
        };
        /** FlagRequest */
        FlagRequest: {
            /** Flag */
            flag: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HideRequest */
        HideRequest: {
            /** Hide */
            hide: boolean;
        };
        /** LayerDTO */
        LayerDTO: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** LayersResponse */
        LayersResponse: {
            /** Layers */
            layers: components["schemas"]["LayerDTO"][];
        };
        /** LocationEntry */
        LocationEntry: {
            /** Mention */
            mention?: string | null;
            /** Name */
            name?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Osm Id */
            osm_id?: string | null;
            /** Osm Type */
            osm_type?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Boundingbox */
            boundingbox?: unknown[] | null;
            /** Polygon */
            polygon?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** LocationsRequest */
        LocationsRequest: {
            /** Locations */
            locations: components["schemas"]["LocationEntry"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Username */
            username: string;
        };
        /** NewCountResponse */
        NewCountResponse: {
            /** Count */
            count: number;
        };
        /** ReportDTO */
        ReportDTO: {
            /** Id */
            id: number;
            /** Identifier */
            identifier: string;
            /** Text */
            text: string;
            /** Url */
            url: string;
            /** Platform */
            platform: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Event Types
             * @default []
             */
            event_types: string[];
            /** Relevance */
            relevance: string;
            /** Processing Status */
            processing_status?: string | null;
            /** Geo Recognition Status */
            geo_recognition_status?: string | null;
            /**
             * Issue Kinds
             * @default []
             */
            issue_kinds: string[];
            /** Author */
            author?: string | null;
            /**
             * Locations
             * @default []
             */
            locations: components["schemas"]["LocationEntry"][];
            /**
             * Original Locations
             * @default []
             */
            original_locations: components["schemas"]["LocationEntry"][];
            /**
             * @default {
             *       "hide": false,
             *       "flag": false,
             *       "new": true
             *     }
             */
            user_state: components["schemas"]["UserStateDTO"];
        };
        /**
         * ReportsBundleResponse
         * @description Reports list + map dots in one payload, so a filter change needs a single
         *     round trip instead of two parallel requests contending on one sync worker.
         */
        ReportsBundleResponse: {
            /** Reports */
            reports: components["schemas"]["ReportDTO"][];
            /** Pending Count */
            pending_count: number;
            /** Loaded At */
            loaded_at: string;
            /** Event Type Totals */
            event_type_totals?: {
                [key: string]: number;
            } | null;
            /** Relevance Totals */
            relevance_totals?: {
                [key: string]: number;
            } | null;
            /** Location Counts */
            location_counts?: {
                [key: string]: number;
            } | null;
            /**
             * Processing Status Totals
             * @default {}
             */
            processing_status_totals: {
                [key: string]: number;
            };
            /**
             * Reports Total Count
             * @default 0
             */
            reports_total_count: number;
            /**
             * Reports Unseen Count
             * @default 0
             */
            reports_unseen_count: number;
            /** All Platforms */
            all_platforms?: string[] | null;
            /** Platform Counts */
            platform_counts?: {
                [key: string]: number;
            } | null;
            /** Platform Added Counts */
            platform_added_counts?: {
                [key: string]: number;
            } | null;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /**
             * Total Count
             * @default 0
             */
            total_count: number;
            /**
             * Unseen Count
             * @default 0
             */
            unseen_count: number;
            /**
             * Dots
             * @default []
             */
            dots: components["schemas"]["DotDTO"][];
        };
        /** ReportsResponse */
        ReportsResponse: {
            /** Reports */
            reports: components["schemas"]["ReportDTO"][];
            /** Pending Count */
            pending_count: number;
            /** Loaded At */
            loaded_at: string;
            /** Event Type Totals */
            event_type_totals?: {
                [key: string]: number;
            } | null;
            /** Relevance Totals */
            relevance_totals?: {
                [key: string]: number;
            } | null;
            /** Location Counts */
            location_counts?: {
                [key: string]: number;
            } | null;
            /**
             * Processing Status Totals
             * @default {}
             */
            processing_status_totals: {
                [key: string]: number;
            };
            /**
             * Reports Total Count
             * @default 0
             */
            reports_total_count: number;
            /**
             * Reports Unseen Count
             * @default 0
             */
            reports_unseen_count: number;
            /** All Platforms */
            all_platforms?: string[] | null;
            /** Platform Counts */
            platform_counts?: {
                [key: string]: number;
            } | null;
            /** Platform Added Counts */
            platform_added_counts?: {
                [key: string]: number;
            } | null;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /**
             * Total Count
             * @default 0
             */
            total_count: number;
            /**
             * Unseen Count
             * @default 0
             */
            unseen_count: number;
        };
        /** ScenarioDTO */
        ScenarioDTO: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** ScenariosResponse */
        ScenariosResponse: {
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioDTO"][];
        };
        /** UserStateDTO */
        UserStateDTO: {
            /**
             * Hide
             * @default false
             */
            hide: boolean;
            /**
             * Flag
             * @default false
             */
            flag: boolean;
            /** Flag Author */
            flag_author?: string | null;
            /**
             * New
             * @default true
             */
            new: boolean;
            /** Locations */
            locations?: components["schemas"]["LocationEntry"][] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VersionResponse
         * @description Opaque change token — see report_service.get_change_token.
         */
        VersionResponse: {
            /** Token */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reports_endpoint_api_v1_reports__get: {
        parameters: {
            query?: {
                loc_filter?: string[];
                platform?: string[];
                event_type?: string[];
                relevance?: string[];
                show_hidden?: boolean;
                show_flagged?: boolean;
                show_unflagged?: boolean;
                limit?: number;
                search?: string | null;
                time_window?: string | null;
                /** @description ISO8601 lower time bound (custom range) */
                since?: string | null;
                /** @description ISO8601 upper time bound (custom range) */
                until?: string | null;
                only_new?: boolean;
                /** @description Show only reports whose extraction pipeline failed */
                only_issues?: boolean;
                /** @description Drawn-area filter: flat 'lat,lon,lat,lon,…' ring */
                area?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    new_count_endpoint_api_v1_reports_new_count_get: {
        parameters: {
            query: {
                /** @description ISO8601 datetime string */
                since: string;
                loc_filter?: string[];
                platform?: string[];
                event_type?: string[];
                relevance?: string[];
                show_hidden?: boolean;
                show_flagged?: boolean;
                show_unflagged?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewCountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_endpoint_api_v1_reports_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dots_endpoint_api_v1_reports_dots_get: {
        parameters: {
            query?: {
                loc_filter?: string[];
                platform?: string[];
                event_type?: string[];
                relevance?: string[];
                show_hidden?: boolean;
                show_flagged?: boolean;
                show_unflagged?: boolean;
                search?: string | null;
                time_window?: string | null;
                /** @description ISO8601 lower time bound (custom range) */
                since?: string | null;
                /** @description ISO8601 upper time bound (custom range) */
                until?: string | null;
                only_new?: boolean;
                only_issues?: boolean;
                /** @description Drawn-area filter: flat 'lat,lon,lat,lon,…' ring */
                area?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DotsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bundle_endpoint_api_v1_reports_bundle_get: {
        parameters: {
            query?: {
                loc_filter?: string[];
                platform?: string[];
                event_type?: string[];
                relevance?: string[];
                show_hidden?: boolean;
                show_flagged?: boolean;
                show_unflagged?: boolean;
                limit?: number;
                search?: string | null;
                time_window?: string | null;
                /** @description ISO8601 lower time bound (custom range) */
                since?: string | null;
                /** @description ISO8601 upper time bound (custom range) */
                until?: string | null;
                only_new?: boolean;
                /** @description Show only reports whose extraction pipeline failed */
                only_issues?: boolean;
                /** @description Drawn-area filter: flat 'lat,lon,lat,lon,…' ring */
                area?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportsBundleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admit_all_endpoint_api_v1_reports_admit_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tour_example_endpoint_api_v1_reports_tour_example_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_endpoint_api_v1_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hide_endpoint_api_v1_reports__report_id__hide_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flag_endpoint_api_v1_reports__report_id__flag_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_endpoint_api_v1_reports__report_id__acknowledge_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_locations_endpoint_api_v1_reports__report_id__locations_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_locations_endpoint_api_v1_reports__report_id__locations_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_layers_api_v1_layers__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    layer_geojson_api_v1_layers__layer_id__geojson_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
            };
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_v1_scenarios__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenariosResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_geojson_api_v1_scenarios__scenario_id__geojson_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: number;
            };
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    user_state_api_v1_user_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nominatim_search_api_v1_geo_nominatim_get: {
        parameters: {
            query: {
                /** @description Search string */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                sems_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_status_api_v1_demo_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    demo_reset_api_v1_demo_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
