FROM python:3.10-slim-bullseye

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install the packages in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Define environment variable, used for determining the host name of the database
ENV IN_DOCKER=true
ENV PYTHONUNBUFFERED=1

# Start the nina server
CMD python ./src/server_nina.py