FROM python:3.10-slim-bullseye

# Set the working directory to /app
WORKDIR /app

# Copy only requirements first
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
# Copy the current directory contents into the container at /app
COPY . .

# Make port 8051 available to the world outside this container
EXPOSE 8051

# Define environment variable, used for determining the host name of the database
ENV IN_DOCKER=true
ENV PYTHONUNBUFFERED=1

# Start the eventserver
CMD python ./src/server_events.py